// Generated by nitro
import type { Serialize, Simplify } from "nitropack/types";
declare module "nitropack/types" {
  type Awaited<T> = T extends PromiseLike<infer U> ? Awaited<U> : T
  interface InternalApi {
    '/api/block': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/block.get').default>>>>
    }
    '/api/menu': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/menu.get').default>>>>
    }
    '/api/model': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/model.get').default>>>>
    }
    '/api/page/:slug': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/page/[slug]').default>>>>
    }
    '/api/site-settings': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/site-settings.get').default>>>>
    }
    '/__nuxt_error': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../node_modules/nuxt/dist/core/runtime/nitro/handlers/renderer').default>>>>
    }
    '/__nuxt_island/**': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/#internal/nuxt/island-renderer').default>>>>
    }
  }
}
export {}